- hosts: all
  become: true

  vars:
    ansible_python_interpreter: '/usr/local/bin/python2.7'

  tasks:
    - include_role:
        name: 'JoergFiedler.freebsd-jailed-nginx'
      vars:
        nginx_pf_redirect: true
        nginx_servers:
          - name: 'freebsd'
            proxy:
              host: 'www.freebsd.org'
              scheme: 'https'
              port: 443
              local: no
        jail_net_ip: '10.1.0.10'
        jail_name: 'nginx'
        jail_freebsd_release: '11.2-RELEASE'
        jail_build_server_enabled: yes
        jail_build_server_url: 'http://vastland.moumantai.de/FreeBSD/packages/freebsd-11_2_x64-branches_2018Q4'
