- src: 'git+https://github.com/JoergFiedler/freebsd-jail-host.git'
  name: 'JoergFiedler.freebsd-jail-host'
- src: 'git+https://github.com/JoergFiedler/freebsd-jailed.git'
  name: 'JoergFiedler.freebsd-jailed'
