---
- name: Check if jail already exists
  shell: /usr/local/sbin/iocage show ip4_addr | grep {{ jail_net_ip }} | cut -d ' ' -f 1
  changed_when: false
  register: jail_uuid

- name: Create jail
  command: /usr/local/sbin/iocage create tag={{ jail_hostname }} ip4_addr={{ jail_net_ip }}
  when: not jail_uuid.stdout
  register: jail_created
  notify:
    - Start iocage

- name: Get jail s UUID
  shell: /usr/local/sbin/iocage show ip4_addr | grep {{ jail_net_ip }} | cut -d ' ' -f 1
  changed_when: false
  register: jail_uuid

- name: Set jail properties
  command: /usr/local/sbin/iocage set {{ item }} {{ jail_uuid.stdout }}
  with_items:
    - 'boot=on'
    - 'hostname={{ jail_hostname }}'
  when: jail_created|changed

- name: Register home diretory
  command: echo {{ host_ioc_jails_dir }}/{{ jail_uuid.stdout }}/root
  changed_when: false
  register: jail_home

