---
- name: Create server s ZFS dataset s mount point
  file: path={{ server_home_host_zfs_dir }}
        state=directory

- name: Create www ZFS dataset
  zfs:  name={{ host_zfs_www_dataset }}
        state=present
        atime=off
        mountpoint={{ host_zfs_www_dir }}

- name: Create server s webroot ZFS dataset
  zfs:  name={{ server_home_host_zfs_dataset }}
        state=present
        atime=off
        mountpoint={{ server_home_host_zfs_dir }}

- name: Create all paths to server s web root
  file: path={{ jail_home.stdout }}{{ server_home }}
        state=directory

- name: Create webroot directory for server
  file: path={{ server_webroot_host_zfs_dir }}
        state=directory

- name: Copy index.html
  copy: src={{ jail_home.stdout }}/usr/local/www/nginx-dist/index.html
        remote_src=yes
        dest={{ server_webroot_host_zfs_dir }}/index.html
        force=no

- name: Configure jail to mount file system from host
  mount: name={{ jail_home.stdout }}{{ server_home }}
         fstab={{ jail_home.stdout }}/../fstab
         fstype=nullfs
         opts=rw
         src={{ server_home_host_zfs_dir }}
         state=present

- name: Backup server home with tarsnap
  template: src=tarsnapper.yml.j2
            dest=/usr/local/etc/tarsnapper.d/{{ server.name}}.yml
  when: tarsnap_keyfile is defined
