---
- name: Install additional packages
  pkgng:
    name: '{{ item }}'
    state: latest
    chroot: '{{ jail_home.stdout }}'
  loop:
    - acme.sh
  register: pkg_result
  until: pkg_result is succeeded

- name: Create SSL key directory
  file:
    path: '{{ jail_home.stdout }}/usr/local/etc/ssl'
    state: directory

- name: Create challenge directory
  file:
    path: '{{ jail_home.stdout }}/var/www/.well-known/acme-challenge'
    state: directory

- name: Create bin directory
  file:
    path: '{{ jail_home.stdout }}/usr/local/bin'
    state: directory

- name: Copy acme.sh weekly script
  template:
    backup: '{{ jail_backup_old_files }}'
    src: 'acme-client-weekly.j2.sh'
    mode: 0700
    dest: '{{ jail_home.stdout }}/usr/local/bin/acme-client-weekly.sh'

- name: Copy acme.sh deploy script
  template:
    backup: '{{ jail_backup_old_files }}'
    src: 'acme-client-deploy.j2.sh'
    mode: 0700
    dest: '{{ jail_home.stdout }}/usr/local/bin/acme-client-deploy.sh'

- name: Make sure acme.sh domain list file exists
  copy:
    force: no
    content: ''
    dest: '{{ jail_home.stdout }}{{ nginx_letsencrypt_domains_file }}'

- name: Copy acme private key if configure
  copy:
    force: no
    src: '{{ nginx_letsencrypt_acme_private_key }}'
    dest: '{{ jail_home.stdout }}{{ nginx_letsencrypt_config_dir }}/privkey.pem'
  when: nginx_letsencrypt_acme_private_key | default(false)

- name: Create periodic folder
  file:
    path: '{{ jail_home.stdout }}/usr/local/etc/periodic/weekly'
    state: directory

- name: Create periodic script
  template:
    backup: '{{ jail_backup_old_files }}'
    src: 'acme-client-periodic.sh.j2'
    mode: 0750
    dest: '{{ jail_home.stdout }}/usr/local/etc/periodic/weekly/000.acme-client.sh'

- name: Make sure /etc/periodic.conf exists
  copy:
    force: no
    content: ''
    dest: '{{ jail_home.stdout }}/etc/periodic.conf'

- name: Refresh certificates using periodic.conf
  blockinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '{{ jail_home.stdout }}/etc/periodic.conf'
    state: present
    marker: '# {mark} run acme-client (Lets Encrypt) every week'
    block: |
      weekly_acme_client_enable="YES"
      weekly_acme_client_renewscript="/usr/local/bin/acme-client-weekly.sh"
      weekly_acme_client_deployscript="/usr/local/bin/acme-client-deploy.sh"
