---
- name: Copy pf configuration (rls)
  template:
    backup: '{{ jail_backup_old_files }}'
    src: 'pf.anchor.rls-jail-proxy.conf.j2'
    dest: '/etc/pf.anchor.rls-jail.{{ jail_name }}-{{ server.name }}.conf'
  when: server.proxy is defined and server.proxy.local
  notify:
    - Reload pf

- name: Add pf configuration to anchor.rls-jail conf
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: /etc/pf.anchor.rls-jail.conf
    state: present
    line: 'include "/etc/pf.anchor.rls-jail.{{ jail_name }}-{{ server.name }}.conf"'
  when: server.proxy is defined and server.proxy.local
  notify:
    - Reload pf

- name: Copy pf configuration (nat)
  template:
    backup: '{{ jail_backup_old_files }}'
    src: 'pf.anchor.nat-jail-proxy.conf.j2'
    dest: '/etc/pf.anchor.nat-jail.{{ jail_name }}-{{ server.name }}.conf'
  when: server.proxy is defined and not server.proxy.local
  notify:
    - Reload pf

- name: Add pf configuration to anchor.nat-jail conf
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: /etc/pf.anchor.nat-jail.conf
    state: present
    line: 'include "/etc/pf.anchor.nat-jail.{{ jail_name }}-{{ server.name }}.conf"'
  when: server.proxy is defined and not server.proxy.local
  notify:
    - Reload pf

- name: Reload pf to allow proxy to reach external origins
  service:
    name: 'pf'
    state: reloaded
  when: server.proxy is defined and not server.proxy.local
