---
- name: Install nginx
  pkgng:
    name: 'nginx'
    state: present
    chroot: '{{ jail_home.stdout }}'

- name: Copy fastcgi params
  copy:
    src: 'fastcgi_params'
    dest: '{{ jail_home.stdout }}/usr/local/etc/nginx/fastcgi_params'

- name: Copy nginx configuration
  template:
    src: 'nginx.conf.j2'
    dest: '{{ jail_home.stdout }}/usr/local/etc/nginx/nginx.conf'

- name: Create directories
  file:
    path: '{{ jail_home.stdout }}/usr/local/etc/nginx/{{ item }}'
    state: directory
  with_items:
    - 'includes'
    - 'ssl'

- name: Create cache directory
  file:
    path: '/var/db/nginx-cache'
    state: directory
    owner: 'www'
    group: 'www'

- name: Enable service
  lineinfile:
    dest: '{{ jail_home.stdout }}/etc/rc.conf'
    state: present
    regexp: '^nginx_enable='
    line: 'nginx_enable="YES"'

- debug: msg={{nginx_servers}}
- include: 'nginx-server.yml'
  with_items:
    - '{{ nginx_servers }}'
