---
- name: Copy pf configuration (rls)
  template:
    src: 'pf.anchor.rls-jail.conf.j2'
    dest: '/etc/pf.anchor.rls-jail.{{ jail_name }}-{{ server.proxy.host }}.conf'
  when: server.proxy is defined
  notify:
    - Reload pf

- name: Add pf configuration to anchor.rls-jail conf
  lineinfile:
    dest: /etc/pf.anchor.nat-jail.conf
    state: present
    line: 'include "/etc/pf.anchor.nat-jail.{{ jail_name }}-{{ server.proxy.host }}.conf"'
  when: server.proxy is defined
  notify:
    - Reload pf

