---
- name: Copy pf configuration (nat rules)
  template:
    src: pf.anchor.nat-jail-https.conf.j2
    dest: /etc/pf.anchor.nat-jail.{{ jail_name }}-https.conf
  notify:
    - Reload pf

- name: Add pf configuration to anchor.nat-jail conf
  lineinfile:
    dest: /etc/pf.anchor.nat-jail.conf
    state: present
    line: 'include "/etc/pf.anchor.nat-jail.{{ jail_name }}-https.conf"'
  notify:
    - Reload pf

- name: Copy pf configuration (rdr rules)
  template:
    src: pf.anchor.rdr-jail-https.conf.j2
    dest: /etc/pf.anchor.rdr-jail.{{ jail_name }}-https.conf
  notify:
    - Reload pf

- name: Add pf configuration to anchor.rdr-jail conf
  lineinfile:
    dest: /etc/pf.anchor.rdr-jail.conf
    state: present
    line: 'include "/etc/pf.anchor.rdr-jail.{{ jail_name }}-https.conf"'
  notify:
    - Reload pf

