---
- name: Copy pf configuration (rdr rules)
  template:
    backup: '{{ jail_backup_old_files }}'
    src: 'pf.anchor.rdr-jail.conf.j2'
    dest: '/etc/pf.anchor.rdr-jail.{{ jail_name }}-{{ item }}.conf'
  loop: '{{ rdr.ports }}'
  notify:
    - Reload pf

- name: Add pf configuration to anchor.rdr-jail conf
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '/etc/pf.anchor.rdr-jail.conf'
    state: present
    line: 'include "/etc/pf.anchor.rdr-jail.{{ jail_name }}-{{ item }}.conf"'
  loop: '{{ rdr.ports }}'
  notify:
    - Reload pf
