---
- name: Copy pf configuration (rdr rules)
  template:
    src: pf.anchor.rdr-jail.conf.j2
    dest: /etc/pf.anchor.rdr-jail.{{ jail_name }}.conf
  notify:
    - Reload pf

- name: Add pf configuration to anchor.rdr-jail conf
  lineinfile:
    dest: /etc/pf.anchor.rdr-jail.conf
    state: present
    line: 'include "/etc/pf.anchor.rdr-jail.{{ jail_name }}.conf"'
  notify:
    - Reload pf

