---
- name: Install ssmtp for easy mail forwarding
  pkgng: name=ssmtp
         state=present
         chroot={{ jail_home.stdout }}

- name: Copy ssmtp.conf into place
  template: src=ssmtp.conf.p2
            dest={{ jail_home.stdout }}/usr/local/etc/ssmtp/ssmtp.conf

- name: Copy mailer configuration into place
  copy: src=mailer.conf
        dest={{ jail_home.stdout }}/etc/mail/mailer.conf
