---
- name: Configure syslog
  lineinfile:
    dest: '{{ jail_home.stdout }}/etc/syslog.conf'
    state: present
    line: '*.*      @{{ syslogd_server }}'
    insertafter: '^#\s+Consult the syslog.conf'
  notify:
    - Reload {{ jail_name }} s syslogd

- name: Enable remote syslog logging
  lineinfile:
    dest: '{{ jail_home.stdout }}/etc/rc.conf'
    regexp: 'syslogd_flags='
    line: 'syslogd_flags=\"-c -s\"'
  notify:
    - Reload {{ jail_name }} s syslogd

