---
# handlers file for jailed_nginx
- name: Reload jail s nginx
  command: |
    /usr/local/bin/iocage exec {{ jail_name }} service nginx reload
  when: jail_created is defined and not jail_created is changed

- name: Reload jails s php-fpm
  command: |
    /usr/local/bin/iocage exec {{ jail_name }} service php-fpm reload
  when: jail_created is defined and not jail_created is changed

- name: Reload jails s sshd
  command: |
    /usr/local/bin/iocage exec {{ jail_name }} service sshd reload
  when: jail_created is defined and not jail_created is changed
