---
# handlers file for jailed_syslogd
- name: Reload jail s nginx
  command: /usr/local/sbin/iocage exec {{ jail_uuid.stdout }} service nginx reload
  when: jail_created is defined and not jail_created|changed
